### ISSUE TITLE
Works on Chrome, not in the app. Also reports missing bracket when none is missing

### ISSUE THREAD

**Issue by FKasa** [yuguang/fiddlesalad#23]
``` HTML
<h1 id="title" >
    Memory
</h1>

<div id="menu" >
    <p onclick="switchTo(playMenu)" >
        Play
    </p>
</div>
<div id="playMenu" >
    GO
</div>
```

---

``` CSS
.current{
    display:block;
    background-color:yellow;
    color:red;
}

.off{
    display:none;
}
```

---

``` JS
function addLoadEvent(func) {
  var oldonload = window.onload;
  if (typeof window.onload != 'function') {
    window.onload = func;
  } else {
    window.onload = function() {
      if (oldonload) {
        oldonload();
      }
      func();
    }
  }
}
//addLoadEvent(nameOfSomeFunctionToRunOnPageLoad);
addLoadEvent(function() {
  document.getElementById("title").className = "current";
});
```
